### PR TITLE
[Resolves #74] Adds better and more descriptive titles

### LINKED ISSUE #74: Regarding titles
The fact that they match the articles is good, but I think they could use more work.

Here's what I'd do:

| Location | Title |
| --- | --- |
| `/` | Down to the Wire |
| `/tags/{tagname}` | Posts tagged {tagname} &mdash; Down to the Wire |
| `/author/{authorname}` | Posts by {authorname} &mdash; Down to the Wire |
| `/posts/{timestamp}` | {articlename} &mdash; Down to the Wire |
| `/admin` | Admin Panel &mdash; Down to the Wire |
| `/editor/{timestamp}` | Editing "{articlename}" &mdash; Down to the Wire |
| `/preview/{timestamp}` | {articlename} (Preview) &mdash; Down to the Wire |

Thoughts?

(Edited: fixed formatting, added missing preview page)

### PR DESCRIPTION
**Pull request by zwade**
Pretty self explanatory, shouldn't cause any problems, but worth a look-over anyway.

(Also I guess I lied about low priority :P )

### CODE REVIEW

**Comment by bluepichu** [comment]
Just browsing over the code quickly, it looks good, but I can't help but feel like we're abusing handlebars here.  Is there any reason that the logic for producing the name can't occur outside of the templating?

**Comment by bluepichu** [comment]
To expand on that thought - why are we setting things inside the template?  We should be able to fill/infer those values before reaching Handlebars.

**Comment by bluepichu** [comment]
Though our templating problems might be something to fix after we merge this rather than at the same time.  Thoughts?

**Comment by bluepichu** [comment]
Template refactor to be handled via #96.

**Comment by bluepichu** [comment]
`/about` and `/contact` didn't get nice titles.  Is this intentional?

I'd also suggest that `/preview/asdf` get the title `asdf (Preview) — Down to the Wire` rather than `(Preview) asdf — Down to the Wire`.

**Comment by zwade** [comment]
`/about` and `/contact` didn't get nice titles because I forgot about them. The `(Preview) ...` versus `... (Preview)` came down to preference on my part, I found `(Preview)` to be higher precedence than the rest of the title

**Comment by bluepichu** [comment]
I'd still argue `... (Preview)` over `(Preview) ...` really only because it could help differentiate multiple previewed pages.  I can take it or leave it, though.

Feel free to merge once `/about` and `/contact` have titles.

**Comment by zwade** [comment]
Merging now

**Pull request merged**
