### PR TITLE
[Fixes #46] Increase left padding on author name

### LINKED ISSUE #46: Corner Cutoff Padding
Currently, names get very close to the edge of the author box. Padding should be increased to account for this.

### PR DESCRIPTION
**Pull request by bluepichu**
Normally, I'd just merge this myself, but I'd like to get in the habit of having someone else actually review pull requests.  (Yes, even the one-liners.)

### CODE REVIEW

**Comment by el1t** [comment]
:+1:

**Comment by bluepichu** [comment]
@el1t If it's good, you can go ahead and click the shiny green "merge pull request" button. :)

**Comment by el1t** [comment]
But multiple code reviews! 
Also it's gray :c

**Comment by bluepichu** [comment]
@el1t True, but keep in mind that by just the two of us thinking it's ok that over 25% of the development group have approved the merge.

**Pull request merged**
